### ISSUE TITLE
object-root.component.spec.ts: ReferenceError: FormUpdatedEvent is not defined

### ISSUE THREAD

**Issue by raboof** [netwerk-digitaal-erfgoed/solid-crs#390]
I wanted to submit a docs contribution, but the commit hook runs the tests, and `packages/solid-crs-presentation/lib/features/object/object-root.component.spec.ts` fails for me:

```
(node:406120) UnhandledPromiseRejectionWarning: ReferenceError: FormUpdatedEvent is not defined
(Use `node --trace-warnings ...` to show where the warning was created)
(node:406120) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
(node:406120) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:406120) UnhandledPromiseRejectionWarning: ReferenceError: FormUpdatedEvent is not defined
(node:406120) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 10)
(node:406120) UnhandledPromiseRejectionWarning: ReferenceError: FormUpdatedEvent is not defined
(node:406120) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 12)
(node:406120) UnhandledPromiseRejectionWarning: ReferenceError: FormUpdatedEvent is not defined
(node:406120) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 14)
(node:406120) UnhandledPromiseRejectionWarning: TypeError: component?.requestUpdate is not a function
(node:406120) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 15)
(node:406120) UnhandledPromiseRejectionWarning: TypeError: component?.requestUpdate is not a function
(node:406120) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 16)
(node:406120) UnhandledPromiseRejectionWarning: TypeError: component?.requestUpdate is not a function
(node:406120) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 17)
(node:406120) UnhandledPromiseRejectionWarning: TypeError: component?.requestUpdate is not a function
(node:406120) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 18)
 FAIL   manage  packages/solid-crs-presentation/lib/features/object/object-root.component.spec.ts
  ● ObjectRootComponent › updated() › should update subscription when formActor is updated

    ReferenceError: FormUpdatedEvent is not defined

      198 |       // needed for validation when coming back from the term machine
      199 |       // otherwise, form machine state is not_validated and the user can't save
    > 200 |       this.formActor.send(new FormUpdatedEvent('name', this.object?.name));
          |                               ^
      201 |
      202 |       this.subscribe('isSubmitting', from(this.formActor).pipe(
      203 |         map((state) => state.matches(FormSubmissionStates.SUBMITTING)),


      at HTMLElement.updated (lib/features/object/object-root.component.ts:200:31)
      at Object.<anonymous> (lib/features/object/object-root.component.spec.ts:234:23)
```

I'm not too familiar with typescript, so this might be something obvious. Things I tried/checked:
* `npm run build:all` succeeded earlier
* `./packages/solid-crs-presentation/lib/features/object/object-root.component.ts` has `import { FormEvent, FormActors, FormSubmissionStates, Alert, FormRootStates, FormCleanlinessStates, FormValidationStates, FormUpdatedEvent } from '@netwerk-digitaal-erfgoed/solid-crs-components'`
* `packages/solid-crs-components/lib/index.ts` has `export * from './forms/form.events';`
* `packages/solid-crs-components/lib/forms/form.events.ts` has `export class FormUpdatedEvent ...`

I'm not sure how to proceed.

**Comment by lem-onade** [comment]
I suggest running `npm run bootstrap`, then retrying. `solid-crs-presentation` is a new package and it's dependencies might not have been installed yet.

**Comment by raboof** [comment]
I re-ran `npm run bootstrap && npm run build:all`. This succeeds but when committing still produces the same test failure.

**Comment by lem-onade** [comment]
I've tried a few things, but can not reproduce. I guess running `npm run test:all` fails as well? Have you tried cloning the repository again?

In the meantime, feel free to include `WIP` in your commit message, then open your PR as usual.

**Comment by raboof** [comment]
> I guess running `npm run test:all` fails as well?

Actually there it is fine :thinking: 

```
@netwerk-digitaal-erfgoed/solid-crs-presentation: Test Suites: 13 passed, 13 total
@netwerk-digitaal-erfgoed/solid-crs-presentation: Tests:       181 passed, 181 total
```

> In the meantime, feel free to include `WIP` in your commit message, then open your PR as usual. This should skip the local tests.

:+1: thanks!

**Comment by raboof** [comment]
Let's close this since it might be something somehow related to my system (I run a somewhat exotic Linux distro, NixOS) and we have a workaround. No need to spend further time on this - unless you want to :)
